# Uncomment the next line to define a global platform for your project
platform :ios, '18'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
    pod 'Mediapiper', :path => '../composeApp'
 #   pod 'MediaPipeTasksGenAI'
 #   pod 'MediaPipeTasksGenAIC'
end
